/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class anchorwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new anchorwestAddonDeed();
			}
		}

		[ Constructable ]
		public anchorwestAddon()
		{
			AddComponent( new AddonComponent( 5368 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5367 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public anchorwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class anchorwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new anchorwestAddon();
			}
		}

		[Constructable]
		public anchorwestAddonDeed()
		{
			Name = "anchor west";
		}

		public anchorwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}