/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class anchorsouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new anchorsouthAddonDeed();
			}
		}

		[ Constructable ]
		public anchorsouthAddon()
		{
			AddComponent( new AddonComponent( 5369 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5370 ), 1, 0, 0 );
			AddonComponent ac = null;

		}

		public anchorsouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class anchorsouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new anchorsouthAddon();
			}
		}

		[Constructable]
		public anchorsouthAddonDeed()
		{
			Name = "anchor south";
		}

		public anchorsouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}