/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class axespearssouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new axespearssouthAddonDeed();
			}
		}

		[ Constructable ]
		public axespearssouthAddon()
		{
			AddComponent( new AddonComponent( 5481 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5480 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public axespearssouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class axespearssouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new axespearssouthAddon();
			}
		}

		[Constructable]
		public axespearssouthAddonDeed()
		{
			Name = "axe and spears south";
		}

		public axespearssouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}