/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class axespearswestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new axespearswestAddonDeed();
			}
		}

		[ Constructable ]
		public axespearswestAddon()
		{
			AddComponent( new AddonComponent( 5482 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public axespearswestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class axespearswestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new axespearswestAddon();
			}
		}

		[Constructable]
		public axespearswestAddonDeed()
		{
			Name = "axe and spears west";
		}

		public axespearswestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}