/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class axewestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new axewestAddonDeed();
			}
		}

		[ Constructable ]
		public axewestAddon()
		{
			AddComponent( new AddonComponent( 5474 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public axewestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class axewestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new axewestAddon();
			}
		}

		[Constructable]
		public axewestAddonDeed()
		{
			Name = "axe west";
		}

		public axewestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}