/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class bodyinwrappingssouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new bodyinwrappingssouthAddonDeed();
			}
		}

		[ Constructable ]
		public bodyinwrappingssouthAddon()
		{
			AddComponent( new AddonComponent( 7564 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 7565 ), 0, 1, 0 );
			AddonComponent ac = null;

		}

		public bodyinwrappingssouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class bodyinwrappingssouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new bodyinwrappingssouthAddon();
			}
		}

		[Constructable]
		public bodyinwrappingssouthAddonDeed()
		{
			Name = "mummy south";
		}

		public bodyinwrappingssouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}