/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class bowarrowswestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new bowarrowswestAddonDeed();
			}
		}

		[ Constructable ]
		public bowarrowswestAddon()
		{
			AddComponent( new AddonComponent( 5470 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public bowarrowswestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class bowarrowswestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new bowarrowswestAddon();
			}
		}

		[Constructable]
		public bowarrowswestAddonDeed()
		{
			Name = "bow and arrows west";
		}

		public bowarrowswestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}