/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class bowarrowssouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new bowarrowssouthAddonDeed();
			}
		}

		[ Constructable ]
		public bowarrowssouthAddon()
		{
			AddComponent( new AddonComponent( 5469 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public bowarrowssouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class bowarrowssouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new bowarrowssouthAddon();
			}
		}

		[Constructable]
		public bowarrowssouthAddonDeed()
		{
			Name = "bow and arrows south";
		}

		public bowarrowssouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}