/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class brickfireplacewestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new brickfireplacewestAddonDeed();
			}
		}

		[ Constructable ]
		public brickfireplacewestAddon()
		{
			AddComponent( new AddonComponent( 2365 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 2359 ), 0, 1, 0 );
			AddonComponent ac = null;

		}

		public brickfireplacewestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class brickfireplacewestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new brickfireplacewestAddon();
			}
		}

		[Constructable]
		public brickfireplacewestAddonDeed()
		{
			Name = "brick fireplace west";
		}

		public brickfireplacewestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}