/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class chaosengravingAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new chaosengravingAddonDeed();
			}
		}

		[ Constructable ]
		public chaosengravingAddon()
		{
			AddComponent( new AddonComponent( 5348 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5347 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5350 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5349 ), 1, 1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5347 );
			AddComponent( ac, 0, 0, 0 );

		}

		public chaosengravingAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class chaosengravingAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new chaosengravingAddon();
			}
		}

		[Constructable]
		public chaosengravingAddonDeed()
		{
			Name = "Chaos Engraving Deed";
		}

		public chaosengravingAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}