/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class coffinwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new coffinwestAddonDeed();
			}
		}

		[ Constructable ]
		public coffinwestAddon()
		{
			AddComponent( new AddonComponent( 7235 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 7234 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 7233 ), -1, 0, 0 );
			AddonComponent ac = null;

		}

		public coffinwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class coffinwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new coffinwestAddon();
			}
		}

		[Constructable]
		public coffinwestAddonDeed()
		{
			Name = "coffin west";
		}

		public coffinwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}