/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class coffinsouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new coffinsouthAddonDeed();
			}
		}

		[ Constructable ]
		public coffinsouthAddon()
		{
			AddComponent( new AddonComponent( 7248 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 7249 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 7247 ), 0, -1, 0 );
			AddonComponent ac = null;

		}

		public coffinsouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class coffinsouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new coffinsouthAddon();
			}
		}

		[Constructable]
		public coffinsouthAddonDeed()
		{
			Name = "coffin south";
		}

		public coffinsouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}