/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class compassionsouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new compassionsouthAddonDeed();
			}
		}

		[ Constructable ]
		public compassionsouthAddon()
		{
			AddComponent( new AddonComponent( 5293 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5292 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5291 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5294 ), 1, 0, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5291 );
			AddComponent( ac, 0, 0, 0 );

		}

		public compassionsouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class compassionsouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new compassionsouthAddon();
			}
		}

		[Constructable]
		public compassionsouthAddonDeed()
		{
			Name = "compassion south";
		}

		public compassionsouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}