/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class compassionwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new compassionwestAddonDeed();
			}
		}

		[ Constructable ]
		public compassionwestAddon()
		{
			AddComponent( new AddonComponent( 5287 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5288 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5289 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5290 ), 1, 0, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5287 );
			AddComponent( ac, 0, 0, 0 );

		}

		public compassionwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class compassionwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new compassionwestAddon();
			}
		}

		[Constructable]
		public compassionwestAddonDeed()
		{ 
			Name = "compassionwest";
		}

		public compassionwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}