/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class fireplacehomeheartwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new fireplacehomeheartwestAddonDeed();
			}
		}

		[ Constructable ]
		public fireplacehomeheartwestAddon()
		{
			AddComponent( new AddonComponent( 9042 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 9041 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public fireplacehomeheartwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class fireplacehomeheartwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new fireplacehomeheartwestAddon();
			}
		}

		[Constructable]
		public fireplacehomeheartwestAddonDeed()
		{
			Name = "fireplace homeheart west";
		}

		public fireplacehomeheartwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}