/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class fishingnetAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new fishingnetAddonDeed();
			}
		}

		[ Constructable ]
		public fishingnetAddon()
		{
			AddComponent( new AddonComponent( 3541 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 3529 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 3530 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 3528 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 3538 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 3539 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 3540 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 3537 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 3531 ), 1, 0, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 3538 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 3539 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 3530 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3528 );
			AddComponent( ac, 0, -1, 0 );

		}

		public fishingnetAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class fishingnetAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new fishingnetAddon();
			}
		}

		[Constructable]
		public fishingnetAddonDeed()
		{
			Name = "fishing net";
		}

		public fishingnetAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}