/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class goldkiteshieldsouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new goldkiteshieldsouthAddonDeed();
			}
		}

		[ Constructable ]
		public goldkiteshieldsouthAddon()
		{
			AddComponent( new AddonComponent( 5488 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public goldkiteshieldsouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class goldkiteshieldsouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new goldkiteshieldsouthAddon();
			}
		}

		[Constructable]
		public goldkiteshieldsouthAddonDeed()
		{
			Name = "gold kite shield south";
		}

		public goldkiteshieldsouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}