/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class goldkiteshieldwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new goldkiteshieldwestAddonDeed();
			}
		}

		[ Constructable ]
		public goldkiteshieldwestAddon()
		{
			AddComponent( new AddonComponent( 5489 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public goldkiteshieldwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class goldkiteshieldwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new goldkiteshieldwestAddon();
			}
		}

		[Constructable]
		public goldkiteshieldwestAddonDeed()
		{
			Name = "gold kite shield west";
		}

		public goldkiteshieldwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}