/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class greykiteshieldwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new greykiteshieldwestAddonDeed();
			}
		}

		[ Constructable ]
		public greykiteshieldwestAddon()
		{
			AddComponent( new AddonComponent( 5487 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public greykiteshieldwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class greykiteshieldwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new greykiteshieldwestAddon();
			}
		}

		[Constructable]
		public greykiteshieldwestAddonDeed()
		{
			Name = "grey kite shield west";
		}

		public greykiteshieldwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}