/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class greyrugAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new greyrugAddonDeed();
			}
		}

		[ Constructable ]
		public greyrugAddon()
		{
			AddComponent( new AddonComponent( 2743 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 2744 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 2740 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 2739 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 2742 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 2746 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 2741 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 2745 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 2747 ), -1, 1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 2744 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2743 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2740 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2739 );
			AddComponent( ac, 0, 0, 0 );

		}

		public greyrugAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class greyrugAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new greyrugAddon();
			}
		}

		[Constructable]
		public greyrugAddonDeed()
		{
			Name = "grey rug";
		}

		public greyrugAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}