/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class greykiteshieldsouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new greykiteshieldsouthAddonDeed();
			}
		}

		[ Constructable ]
		public greykiteshieldsouthAddon()
		{
			AddComponent( new AddonComponent( 5486 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public greykiteshieldsouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class greykiteshieldsouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new greykiteshieldsouthAddon();
			}
		}

		[Constructable]
		public greykiteshieldsouthAddonDeed()
		{
			Name = "grey kite shield south";
		}

		public greykiteshieldsouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}