/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class hangingpolesouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new hangingpolesouthAddonDeed();
			}
		}

		[ Constructable ]
		public hangingpolesouthAddon()
		{
			AddComponent( new AddonComponent( 4273 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 4271 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 4272 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public hangingpolesouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class hangingpolesouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new hangingpolesouthAddon();
			}
		}

		[Constructable]
		public hangingpolesouthAddonDeed()
		{
			Name = "hanging pole south";
		}

		public hangingpolesouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}