/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class hangingpolewestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new hangingpolewestAddonDeed();
			}
		}

		[ Constructable ]
		public hangingpolewestAddon()
		{
			AddComponent( new AddonComponent( 4270 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 4268 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 4269 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public hangingpolewestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class hangingpolewestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new hangingpolewestAddon();
			}
		}

		[Constructable]
		public hangingpolewestAddonDeed()
		{
			Name = "hanging pole west";
		}

		public hangingpolewestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}