/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class honestywestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new honestywestAddonDeed();
			}
		}

		[ Constructable ]
		public honestywestAddon()
		{
			AddComponent( new AddonComponent( 5281 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5280 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5279 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5282 ), 1, 0, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5279 );
			AddComponent( ac, 0, 0, 0 );

		}

		public honestywestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class honestywestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new honestywestAddon();
			}
		}

		[Constructable]
		public honestywestAddonDeed()
		{
			Name = "honesty west";
		}

		public honestywestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}