/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class honestysouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new honestysouthAddonDeed();
			}
		}

		[ Constructable ]
		public honestysouthAddon()
		{
			AddComponent( new AddonComponent( 5286 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5285 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5284 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5283 ), 0, 0, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5283 );
			AddComponent( ac, 0, 0, 0 );

		}

		public honestysouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class honestysouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new honestysouthAddon();
			}
		}

		[Constructable]
		public honestysouthAddonDeed()
		{
			Name = "honesty south";
		}

		public honestysouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}