/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class honorsouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new honorsouthAddonDeed();
			}
		}

		[ Constructable ]
		public honorsouthAddon()
		{
			AddComponent( new AddonComponent( 5324 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5323 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5326 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5325 ), 1, 1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5323 );
			AddComponent( ac, 0, 0, 0 );

		}

		public honorsouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class honorsouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new honorsouthAddon();
			}
		}

		[Constructable]
		public honorsouthAddonDeed()
		{
			Name = "honor south";
		}

		public honorsouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}