/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class honorwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new honorwestAddonDeed();
			}
		}

		[ Constructable ]
		public honorwestAddon()
		{
			AddComponent( new AddonComponent( 5319 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5322 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5321 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5320 ), 0, 1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5319 );
			AddComponent( ac, 0, 0, 0 );

		}

		public honorwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class honorwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new honorwestAddon();
			}
		}

		[Constructable]
		public honorwestAddonDeed()
		{
			Name = "honor west";
		}

		public honorwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}