/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class humilitywestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new humilitywestAddonDeed();
			}
		}

		[ Constructable ]
		public humilitywestAddon()
		{
			AddComponent( new AddonComponent( 5330 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5329 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5327 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5328 ), 0, 1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5327 );
			AddComponent( ac, 0, 0, 0 );

		}

		public humilitywestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class humilitywestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new humilitywestAddon();
			}
		}

		[Constructable]
		public humilitywestAddonDeed()
		{
			Name = "humility west";
		}

		public humilitywestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}