/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class humilitysouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new humilitysouthAddonDeed();
			}
		}

		[ Constructable ]
		public humilitysouthAddon()
		{
			AddComponent( new AddonComponent( 5332 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5333 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5334 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5331 ), 0, 0, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5331 );
			AddComponent( ac, 0, 0, 0 );

		}

		public humilitysouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class humilitysouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new humilitysouthAddon();
			}
		}

		[Constructable]
		public humilitysouthAddonDeed()
		{
			Name = "humility south";
		}

		public humilitysouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}