/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class justicesouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new justicesouthAddonDeed();
			}
		}

		[ Constructable ]
		public justicesouthAddon()
		{
			AddComponent( new AddonComponent( 5301 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5300 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5299 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5302 ), 1, 0, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5299 );
			AddComponent( ac, 0, 0, 0 );

		}

		public justicesouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class justicesouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new justicesouthAddon();
			}
		}

		[Constructable]
		public justicesouthAddonDeed()
		{
			Name = "justice south";
		}

		public justicesouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}