/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class largegoldenfloralrugAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new largegoldenfloralrugAddonDeed();
			}
		}

		[ Constructable ]
		public largegoldenfloralrugAddon()
		{
			AddComponent( new AddonComponent( 2778 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 2778 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 2784 ), 2, -2, 0 );
			AddComponent( new AddonComponent( 2778 ), 2, -1, 0 );
			AddComponent( new AddonComponent( 2778 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 2779 ), 3, 2, 0 );
			AddComponent( new AddonComponent( 2785 ), 3, 1, 0 );
			AddComponent( new AddonComponent( 2785 ), 3, 0, 0 );
			AddComponent( new AddonComponent( 2785 ), 3, -1, 0 );
			AddComponent( new AddonComponent( 2782 ), 3, -2, 0 );
			AddComponent( new AddonComponent( 2778 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 2778 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 2784 ), 0, -2, 0 );
			AddComponent( new AddonComponent( 2778 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 2784 ), -2, -2, 0 );
			AddComponent( new AddonComponent( 2778 ), -2, -1, 0 );
			AddComponent( new AddonComponent( 2778 ), -2, 0, 0 );
			AddComponent( new AddonComponent( 2778 ), -2, 1, 0 );
			AddComponent( new AddonComponent( 2778 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 2786 ), 2, 2, 0 );
			AddComponent( new AddonComponent( 2786 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 2786 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 2786 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 2778 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 2778 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 2778 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 2784 ), -1, -2, 0 );
			AddComponent( new AddonComponent( 2783 ), -3, -1, 0 );
			AddComponent( new AddonComponent( 2780 ), -3, -2, 0 );
			AddComponent( new AddonComponent( 2783 ), -3, 1, 0 );
			AddComponent( new AddonComponent( 2783 ), -3, 0, 0 );
			AddComponent( new AddonComponent( 2786 ), -2, 2, 0 );
			AddComponent( new AddonComponent( 2781 ), -3, 2, 0 );
			AddComponent( new AddonComponent( 2778 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 2784 ), 1, -2, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 2780 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 2783 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 2783 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 2783 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 2781 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 2784 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 2784 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 2784 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 2784 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 2784 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 2786 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 2786 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 2786 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 2786 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 2786 );
			AddComponent( ac, 2, 2, 0 );

		}

		public largegoldenfloralrugAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class largegoldenfloralrugAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new largegoldenfloralrugAddon();
			}
		}

		[Constructable]
		public largegoldenfloralrugAddonDeed()
		{
			Name = "large golden floral rug";
		}

		public largegoldenfloralrugAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}