/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class largefloralrugwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new largefloralrugwestAddonDeed();
			}
		}

		[ Constructable ]
		public largefloralrugwestAddon()
		{
			AddComponent( new AddonComponent( 2805 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 2797 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 2797 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 2797 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 2803 ), 1, -2, 0 );
			AddComponent( new AddonComponent( 2797 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 2801 ), 3, -2, 0 );
			AddComponent( new AddonComponent( 2804 ), 3, -1, 0 );
			AddComponent( new AddonComponent( 2796 ), -2, -1, 0 );
			AddComponent( new AddonComponent( 2803 ), -2, -2, 0 );
			AddComponent( new AddonComponent( 2797 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 2797 ), -2, 0, 0 );
			AddComponent( new AddonComponent( 2802 ), -3, 0, 0 );
			AddComponent( new AddonComponent( 2802 ), -3, 1, 0 );
			AddComponent( new AddonComponent( 2804 ), 3, 0, 0 );
			AddComponent( new AddonComponent( 2805 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 2796 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 2797 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 2796 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 2803 ), 0, -2, 0 );
			AddComponent( new AddonComponent( 2796 ), 2, -1, 0 );
			AddComponent( new AddonComponent( 2803 ), 2, -2, 0 );
			AddComponent( new AddonComponent( 2799 ), -3, -2, 0 );
			AddComponent( new AddonComponent( 2802 ), -3, -1, 0 );
			AddComponent( new AddonComponent( 2803 ), -1, -2, 0 );
			AddComponent( new AddonComponent( 2797 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 2796 ), -2, 1, 0 );
			AddComponent( new AddonComponent( 2797 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 2805 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 2805 ), -2, 2, 0 );
			AddComponent( new AddonComponent( 2796 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 2804 ), 3, 1, 0 );
			AddComponent( new AddonComponent( 2798 ), 3, 2, 0 );
			AddComponent( new AddonComponent( 2805 ), 2, 2, 0 );
			AddComponent( new AddonComponent( 2800 ), -3, 2, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 2799 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 2802 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 2802 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 2802 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 2803 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 2803 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 2803 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 2803 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 2803 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2796 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 2797 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2797 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2797 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2797 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2797 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2796 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 2797 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2797 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2796 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2796 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2797 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 2797 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 2796 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2796 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 2801 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 2804 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 2804 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 2804 );
			AddComponent( ac, 3, 1, 0 );

		}

		public largefloralrugwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class largefloralrugwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new largefloralrugwestAddon();
			}
		}

		[Constructable]
		public largefloralrugwestAddonDeed()
		{
			Name = "large floral rug west";
		}

		public largefloralrugwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}