/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class logtablesouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new logtablesouthAddonDeed();
			}
		}

		[ Constructable ]
		public logtablesouthAddon()
		{
			AddComponent( new AddonComponent( 4576 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 4577 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 4575 ), 0, 1, 0 );
			AddonComponent ac = null;

		}

		public logtablesouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class logtablesouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new logtablesouthAddon();
			}
		}

		[Constructable]
		public logtablesouthAddonDeed()
		{
			Name = "log table south";
		}

		public logtablesouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}