/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class minigoldfloralrugAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new minigoldfloralrugAddonDeed();
			}
		}

		[ Constructable ]
		public minigoldfloralrugAddon()
		{
			AddComponent( new AddonComponent( 2782 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 2785 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 2780 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 2783 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 2781 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 2779 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 2786 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 2778 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 2784 ), 0, -1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 2780 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2783 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2784 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 0, 0, 0 );

		}

		public minigoldfloralrugAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class minigoldfloralrugAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new minigoldfloralrugAddon();
			}
		}

		[Constructable]
		public minigoldfloralrugAddonDeed()
		{
			Name = "mini gold floral rug";
		}

		public minigoldfloralrugAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}