/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class orecartwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new orecartwestAddonDeed();
			}
		}

		[ Constructable ]
		public orecartwestAddon()
		{
			AddComponent( new AddonComponent( 6795 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 6792 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 6791 ), 1, 0, 0 );
			AddonComponent ac = null;

		}

		public orecartwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class orecartwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new orecartwestAddon();
			}
		}

		[Constructable]
		public orecartwestAddonDeed()
		{
			Name = "ore cart west";
		}

		public orecartwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}