/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class orecartsouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new orecartsouthAddonDeed();
			}
		}

		[ Constructable ]
		public orecartsouthAddon()
		{
			AddComponent( new AddonComponent( 6786 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 6787 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 6790 ), 0, -1, 0 );
			AddonComponent ac = null;

		}

		public orecartsouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class orecartsouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new orecartsouthAddon();
			}
		}

		[Constructable]
		public orecartsouthAddonDeed()
		{
			Name = "ore cart south";
		}

		public orecartsouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}