/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class redrugAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new redrugAddonDeed();
			}
		}

		[ Constructable ]
		public redrugAddon()
		{
			AddComponent( new AddonComponent( 2737 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 2736 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 2731 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 2735 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 2733 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 2734 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 2730 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 2729 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 2732 ), 0, 1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 2734 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2733 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2730 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2729 );
			AddComponent( ac, 0, 0, 0 );

		}

		public redrugAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class redrugAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new redrugAddon();
			}
		}

		[Constructable]
		public redrugAddonDeed()
		{
			Name = "red rug";
		}

		public redrugAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}