/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class roundshieldwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new roundshieldwestAddonDeed();
			}
		}

		[ Constructable ]
		public roundshieldwestAddon()
		{
			AddComponent( new AddonComponent( 5485 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public roundshieldwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class roundshieldwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new roundshieldwestAddon();
			}
		}

		[Constructable]
		public roundshieldwestAddonDeed()
		{
			Name = "round shield west";
		}

		public roundshieldwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}