/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class rune2Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new rune2AddonDeed();
			}
		}

		[ Constructable ]
		public rune2Addon()
		{
			AddComponent( new AddonComponent( 3687 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public rune2Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class rune2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new rune2Addon();
			}
		}

		[Constructable]
		public rune2AddonDeed()
		{
			Name = "rune 2";
		}

		public rune2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}