/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class sacrifisesouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new sacrifisesouthAddonDeed();
			}
		}

		[ Constructable ]
		public sacrifisesouthAddon()
		{
			AddComponent( new AddonComponent( 5391 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5390 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5393 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5392 ), 1, 1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5390 );
			AddComponent( ac, 0, 0, 0 );

		}

		public sacrifisesouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class sacrifisesouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new sacrifisesouthAddon();
			}
		}

		[Constructable]
		public sacrifisesouthAddonDeed()
		{
			Name = "sacrifice south";
		}

		public sacrifisesouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}