/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class sacrifisewestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new sacrifisewestAddonDeed();
			}
		}

		[ Constructable ]
		public sacrifisewestAddon()
		{
			AddComponent( new AddonComponent( 5386 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5387 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5388 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5389 ), 1, 0, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5386 );
			AddComponent( ac, 0, 0, 0 );

		}

		public sacrifisewestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class sacrifisewestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new sacrifisewestAddon();
			}
		}

		[Constructable]
		public sacrifisewestAddonDeed()
		{
			Name = "sacrifice west";
		}

		public sacrifisewestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}