/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class sandstonefireplacesouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new sandstonefireplacesouthAddonDeed();
			}
		}

		[ Constructable ]
		public sandstonefireplacesouthAddon()
		{
			AddComponent( new AddonComponent( 1154 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 1147 ), 1, 0, 0 );
			AddonComponent ac = null;

		}

		public sandstonefireplacesouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class sandstonefireplacesouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new sandstonefireplacesouthAddon();
			}
		}

		[Constructable]
		public sandstonefireplacesouthAddonDeed()
		{
			Name = "sandstone fireplace south";
		}

		public sandstonefireplacesouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}