/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class sandstonefireplacewestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new sandstonefireplacewestAddonDeed();
			}
		}

		[ Constructable ]
		public sandstonefireplacewestAddon()
		{
			AddComponent( new AddonComponent( 1141 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 1161 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public sandstonefireplacewestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class sandstonefireplacewestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new sandstonefireplacewestAddon();
			}
		}

		[Constructable]
		public sandstonefireplacewestAddonDeed()
		{
			Name = "sandstone fireplace west";
		}

		public sandstonefireplacewestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}