/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class sandstoneovensouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new sandstoneovensouthAddonDeed();
			}
		}

		[ Constructable ]
		public sandstoneovensouthAddon()
		{
			AddComponent( new AddonComponent( 1135 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 1132 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public sandstoneovensouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class sandstoneovensouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new sandstoneovensouthAddon();
			}
		}

		[Constructable]
		public sandstoneovensouthAddonDeed()
		{
			Name = "sandstone oven south";
		}

		public sandstoneovensouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}