/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class sandstoneovenwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new sandstoneovenwestAddonDeed();
			}
		}

		[ Constructable ]
		public sandstoneovenwestAddon()
		{
			AddComponent( new AddonComponent( 1121 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 1122 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public sandstoneovenwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class sandstoneovenwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new sandstoneovenwestAddon();
			}
		}

		[Constructable]
		public sandstoneovenwestAddonDeed()
		{
			Name = "sandstone oven west";
		}

		public sandstoneovenwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}