/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class shieldweaponwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new shieldweaponwestAddonDeed();
			}
		}

		[ Constructable ]
		public shieldweaponwestAddon()
		{
			AddComponent( new AddonComponent( 5687 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public shieldweaponwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class shieldweaponwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new shieldweaponwestAddon();
			}
		}

		[Constructable]
		public shieldweaponwestAddonDeed()
		{
			Name = "shield and weapon west";
		}

		public shieldweaponwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}