/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class smallbluedecorativerugAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new smallbluedecorativerugAddonDeed();
			}
		}

		[ Constructable ]
		public smallbluedecorativerugAddon()
		{
			AddComponent( new AddonComponent( 2808 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 2808 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 2755 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 2806 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 2806 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 2756 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 2809 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 2809 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 2751 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 2751 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 2807 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 2807 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 2757 ), 2, -1, 0 );
			AddComponent( new AddonComponent( 2751 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 2751 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 2754 ), 2, 2, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 2806 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2807 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 2755 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2806 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2807 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 0, 1, 0 );

		}

		public smallbluedecorativerugAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class smallbluedecorativerugAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new smallbluedecorativerugAddon();
			}
		}

		[Constructable]
		public smallbluedecorativerugAddonDeed()
		{
			Name = "small blue decorative rug";
		}

		public smallbluedecorativerugAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}