/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class spiritualitywestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new spiritualitywestAddonDeed();
			}
		}

		[ Constructable ]
		public spiritualitywestAddon()
		{
			AddComponent( new AddonComponent( 5312 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5311 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5314 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5313 ), 1, 1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5311 );
			AddComponent( ac, 0, 0, 0 );

		}

		public spiritualitywestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class spiritualitywestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new spiritualitywestAddon();
			}
		}

		[Constructable]
		public spiritualitywestAddonDeed()
		{
			Name = "spirituality west";
		}

		public spiritualitywestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}