/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class spiritualitysouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new spiritualitysouthAddonDeed();
			}
		}

		[ Constructable ]
		public spiritualitysouthAddon()
		{
			AddComponent( new AddonComponent( 5315 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5316 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5317 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5318 ), 1, 0, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5315 );
			AddComponent( ac, 0, 0, 0 );

		}

		public spiritualitysouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class spiritualitysouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new spiritualitysouthAddon();
			}
		}

		[Constructable]
		public spiritualitysouthAddonDeed()
		{
			Name = "spirituality south";
		}

		public spiritualitysouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}