/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class swordswestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new swordswestAddonDeed();
			}
		}

		[ Constructable ]
		public swordswestAddon()
		{
			AddComponent( new AddonComponent( 5478 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5479 ), 0, 0, 0 );
			AddonComponent ac = null;

		}

		public swordswestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class swordswestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new swordswestAddon();
			}
		}

		[Constructable]
		public swordswestAddonDeed()
		{
			Name = "swords west";
		}

		public swordswestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}