/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class tablewithclothsouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new tablewithclothsouthAddonDeed();
			}
		}

		[ Constructable ]
		public tablewithclothsouthAddon()
		{
			AddComponent( new AddonComponent( 5737 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 5736 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5735 ), 0, 1, 0 );
			AddonComponent ac = null;

		}

		public tablewithclothsouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class tablewithclothsouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new tablewithclothsouthAddon();
			}
		}

		[Constructable]
		public tablewithclothsouthAddonDeed()
		{
			Name = "covered table south";
		}

		public tablewithclothsouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}