/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class tablewithclothwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new tablewithclothwestAddonDeed();
			}
		}

		[ Constructable ]
		public tablewithclothwestAddon()
		{
			AddComponent( new AddonComponent( 5740 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5739 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5738 ), -1, 0, 0 );
			AddonComponent ac = null;

		}

		public tablewithclothwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class tablewithclothwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new tablewithclothwestAddon();
			}
		}

		[Constructable]
		public tablewithclothwestAddonDeed()
		{
			Name = "covered table west";
		}

		public tablewithclothwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}