/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class valorwestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new valorwestAddonDeed();
			}
		}

		[ Constructable ]
		public valorwestAddon()
		{
			AddComponent( new AddonComponent( 5303 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5306 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 5305 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5304 ), 0, 1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5303 );
			AddComponent( ac, 0, 0, 0 );

		}

		public valorwestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class valorwestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new valorwestAddon();
			}
		}

		[Constructable]
		public valorwestAddonDeed()
		{
			Name = "valor west";
		}

		public valorwestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}