/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class valorsouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new valorsouthAddonDeed();
			}
		}

		[ Constructable ]
		public valorsouthAddon()
		{
			AddComponent( new AddonComponent( 5309 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 5308 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 5307 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 5310 ), 1, 0, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 5307 );
			AddComponent( ac, 0, 0, 0 );

		}

		public valorsouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class valorsouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new valorsouthAddon();
			}
		}

		[Constructable]
		public valorsouthAddonDeed()
		{
			Name = "valor south";
		}

		public valorsouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}